---
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    - namespace="robertdebock/"
  matrix:
    - image="docker-alpine-openrc"
    - image="docker-alpine-openrc" tag="edge"
    # - namespace="archlinux/" image="base"
    - image="docker-centos-systemd" tag="7"
    - image="docker-centos-systemd"
    - image="docker-debian-systemd" tag="stable"
    - image="docker-debian-systemd" tag="unstable"
    - image="docker-debian-systemd"
    - image="docker-fedora-systemd"
    - image="docker-fedora-systemd" tag="rawhide"
    - namespace="opensuse/" image="leap"
    - image="docker-ubuntu-systemd" tag="rolling"
    - image="docker-ubuntu-systemd" tag="devel"
    - image="docker-ubuntu-systemd"

matrix:
  allow_failures:
    - env: image="docker-alpine-openrc" tag="edge"
    - env: image="docker-debian-systemd" tag="unstable"
    - env: image="docker-fedora-systemd" tag="rawhide"
    - env: image="docker-ubuntu-systemd" tag="rolling"
    - env: image="docker-ubuntu-systemd" tag="devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "LmW+3578U7MAUOTYbf4ZcZclQWVlh6j9aKr7DbyHSG9OiVqfgb2U4aea3rLTRAw8EE/WgQRL61Pm8YJ/F0yCRcVlaeOEUNmOjkVTKrWGd3XXK079Ek+lPYFL3ozsnUv4tpP71wtkLzzCAkJABBW+Z9pUN+02IOQV2Lu9VXprxppWZEuNfNjfWhwUZwpfUok7WD93/59zoKNHU9wnI/xVNVFpBIsViGoSTx5TU9+mVPhXKKmDPL2EulJQn1QFiwAfcnWdQuECGCvuZa7d8z1JLFfcWksJ7mk2bHL/5WJt3lddT3l9sWXDZ1SP8RbYsoseT5/YwHGc6ubILGuOtzOV34MdAYIR9Y8X5FMbVbTlDfPQVbVyv6bvp6hq4G/WLFA0o591rM1P+wQ0BEGsHs06z2j/YJSveLblRQeKZeMURcG1d6tfknp4pvQFpG80Efbm3Ux0iE/ST03MYXbyktP+jhpkSeRG+KopgxNqgEeicpsIa6L4rctSDFuQqtZfVBQCmrGsEG9Iv727EMw7565n5uJJmwRz0PaCQkqhu+fUPPvpw+itBvGrvtUX8h9IjuDk7C3NiL20baJ6OMvbklHOF8b20DqE5BwHcoDESxA6aQat1yo/dwushXhAfP+vSfG22HSNXIDj2Tq0PRrtZqUTkWFJe8skt67XgxUyfKkcABE="
  email: false
