---

- name: test if vagrant_version is set correctly
  assert:
    that:
      - vagrant_version is defined
    quiet: yes

- name: test if vagrant_unarchive_dest is set correctly
  assert:
    that:
      - vagrant_unarchive_dest is defined
    quiet: yes
