---
# tasks file for vagrant
- name: include assert.yml
  include_tasks: assert.yml

- name: download vagrant
  get_url:
    url: "{{ vagrant_package }}"
    dest: /tmp

- name: install vagrant rpm using package
  package:
    name: "/tmp/{{ vagrant_package | basename }}"
    state: present
    disable_gpg_check: yes
  when:
    - ansible_pkg_mgr == "yum" or
      ansible_pkg_mgr == "dnf"

- name: install vagrant rpm using zypper
  zypper:
    name: "/tmp/{{ vagrant_package | basename }}"
    state: present
    disable_gpg_check: yes
  when:
    - ansible_pkg_mgr == "zypper"

- name: install vagrant deb
  apt:
    deb: "/tmp/{{ vagrant_package | basename }}"
    state: present
  when:
    - ansible_pkg_mgr == "apt"

- name: install vagrant archive
  unarchive:
    src: "/tmp/{{ vagrant_package | basename }}"
    dest: "{{ vagrant_unarchive_dest }}"
    creates: "{{ vagrant_unarchive_dest }}/vagrant"
    remote_src: yes
    mode: "0755"
  when:
    - ansible_pkg_mgr != "apt"
    - ansible_pkg_mgr != "yum"
    - ansible_pkg_mgr != "dnf"
    - ansible_pkg_mgr != "zypper"

- name: install pip requirements
  pip:
    name: "{{ vagrant_pip_packages }}"
    state: present
